name: Kibot build

on:
  push:

jobs:
  kibot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot_build.yml
        dir: kibot_outputs
        schema: 'kicad/voltix-solar-shield.kicad_sch'
        board: 'kicad/voltix-solar-shield.kicad_pcb'

    - name: Force permissions (kibot messes them up)
      run: sudo chown -R 1001:1001 kibot_outputs

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: kibot_outputs
